### ISSUE TITLE
MODULE_NOT_FOUND in tesseract.js electron sample

### ISSUE THREAD

**Issue by H0rn0chse** [naptha/tesseract.js#493]
Hello,
The electron sample does not work for me with the latest version.
It works on 2.1.3. Thanks in advance.

```
Error: Cannot find module 'D:\Aaron\Documents\tesseract.js-electron\file:\D:\Aaron\Documents\tesseract.js-electron\node_modules\tesseract.js\src\worker-script\node\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
```

**To Reproduce**
1. Checkout the sample: [https://github.com/jeromewu/tesseract.js-electron](https://github.com/jeromewu/tesseract.js-electron)
2. Bump tesseract.js to the latest version 2.1.4
3. run application

**Desktop:**
 - OS: Windows 10
 - Node: 14.4.0

**Comment by nicoseijas** [comment]
I have the same problem in an Electron App:

`Error: Cannot find module 'E:\MyApp\file:\E:\MyApp\node_modules\tesseract.js\src\worker-script\node\index.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:972:15)
    at Module._load (internal/modules/cjs/loader.js:848:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}`

Looking out the code I found that the module path is wrong: `E:\MyApp\file:\E:\MyApp`

This is a piece of my code I been using to test Tesseract:

`const { createWorker } = require('tesseract.js');`

`const worker = createWorker({
                      logger: m => console.log(m),
                    });
              
                    (async () => {
                      await worker.load();
                      await worker.loadLanguage('eng');
                      await worker.initialize('eng');
                      const { data: { text } } = await worker.recognize('https://cdn.ragan.com/wp-content/uploads/2017/06/One_Word-1.jpg');
                      console.log(text);
                      await worker.terminate();
                    })();`

**Comment by stoma655** [comment]
I have the same problem now, I cannot solve ((

**Comment by MomasVII** [comment]
Did you find a solution for this?

**Comment by H0rn0chse** [comment]
I stayed on 2.1.3 for now

**Comment by MomasVII** [comment]
Damn, I went back to 2.1.3 and still get this issue....

      internal/modules/cjs/loader.js:818
      throw err;
      ^
      Error: Cannot find module '/worker-script/node/index.js'
      at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
      at Function.Module._load (internal/modules/cjs/loader.js:667:27)
      at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
      at internal/main/run_main_module.js:17:47 {
      code: 'MODULE_NOT_FOUND',
      requireStack: []
      }
      END RequestId: aefed3fa-8882-4fca-be6f-6946a736ea90
      REPORT RequestId: aefed3fa-8882-4fca-be6f-6946a736ea90 Duration: 10010.41 ms Billed Duration: 10000 ms Memory Size:       512 MB Max Memory Used: 291 MB
      2021-05-20T07:17:05.949Z aefed3fa-8882-4fca-be6f-6946a736ea90 Task timed out after 10.01 seconds

Any ideas would be amazing

**Comment by knmr** [comment]
I decided to move the tesseract.js part to renderer and that works.

**Comment by MomasVII** [comment]
> I decided to move the tesseract.js part to renderer and that works.

Can you explain a bit more please?

**Comment by knmr** [comment]
> > I decided to move the tesseract.js part to renderer and that works.
> 
> Can you explain a bit more please?

Yes of course.

Previously I read the file from disk and started the OCR process from background.ts. This gave me a MODULE_NOT_FOUND error. What I do now is read the file and send it to the frontend using [ipcMain](https://www.electronjs.org/docs/api/ipc-main).

background.ts
`app.on('ready', async () => {
	ipcMain.on('screenshotRequest', (event, arg) => {
		Jimp.read(`./screenshots/${arg}`).then((image) => {
			image.getBase64Async('image/png').then((contents) => {
				event.reply('screenshotRequest', {
					fileName: arg,
					base64Image: contents,
				});
			});
		});
	});
	createWindow();
});
`

frontendcomponent.vue
`
import Ocr from '../background/ocr';
// register the event
ipcRenderer.on('screenshotRequest', this.loadImage);
...
// request a file
window.ipcRenderer.send('screenshotRequest', fileName);
// handling the received image
async loadImage(event: unknown, data: ScreenshotRequestEvent) {
const imageBuffer = Buffer.from(data.base64Image.replace(/^data:image\/png;base64,/, ''), 'base64');
Ocr.handleScreenshot(imageBuffer).then((e) => {
	// do stuff
}
`

**Comment by cdbst** [comment]
i have same problem on v2.1.5

**Comment by Balearica** [comment]
See this example.

https://github.com/Balearica/tesseract.js-electron

**Comment by Balearica** [comment]
Closing this issue as Tesseract.js v2 is multiple years old and no longer supported.  Feel free to open a new issue (with a reproducible example) if you are unable to use Electron with the current version.  See the repo linked below for a basic example.

https://github.com/Balearica/tesseract.js-electron
